### ISSUE TITLE
Meme-list with links? (feature request)

### ISSUE THREAD

**Issue by tomkiss** [nicolewhite/slack-meme#12]
LOVE this. It's just the best.

The only thing I would like to suggest is that, as I don't know ALL the memes (my bad), it'd be handy to have a link to the appropriate http://knowyourmeme.com page when calling up the /meme-list command - as I find myself copying the text, pasting in to Google to check them.

I suppose the best case scenario would be a tiny thumbnail or a grid of thumbnails with links, so at-a-glance you can find the one you're looking for. But either way - making it easier to check or preview the memes would be ace.

:heart:

**Comment by nicolewhite** [comment]
Hey, so you can test out your memes by going into the slackbot channel and messing around there. But I don't think this would hurt. I suppose I could change `/meme templates` to link to the respective meme pages?

**Comment by tomkiss** [comment]
That would be ace :D

**Comment by zephirefaith** [comment]
Can I take a crack at this? I looked at the get_templates() function and the only thing I need to do is extract the knowyourmeme web address from JSON and add that as a new field into the template list. I will also modify the list_templates to print all three fields rather than two.

**Comment by nicolewhite** [comment]
Please do. It's not hard I've just been really lazy. :(

**Comment by zephirefaith** [comment]
I can't test the app though, I am facing the same error as in #13 with my test API token

**Comment by nicolewhite** [comment]
Me neither; I haven't used it since I left my last job. :(

I'll try to get it set up on a new Slack team to test your changes.
