### ISSUE TITLE
Getting an Internal Server Error?

### ISSUE THREAD

**Issue by Dgolborne** [nicolewhite/slack-meme#13]
First time testing this out in my private slack I received the following:
`DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"
500 Internal Server Error
Internal Server Error
The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.`

Tried updating but after "git pull --rebase slack-meme master" I attempted to git push heroku master and I was told the following:

`! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://git.heroku.com/cryptic-beyond-96990.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.`

Sorry I'm new at this so would appreciate any help you can give!

**Comment by nicolewhite** [comment]
Can you check your logs and see what went wrong? Or enable debug mode?

**Comment by kmelve** [comment]
The app breaks on a key error on 

```
response = requests.get(url)
user = response.json()["user"]
```

Most likely because your API TOKEN is invalid. I suspect it's because Slack has gone OAuth, which requires you to authenticate the app before you can use it. I was able to make it work with the [Test token](https://api.slack.com/docs/oauth-test-tokens), but this isn't really a good method if you plan to use the app for your team.

**Comment by nicolewhite** [comment]
Their new system doesn't really work here because I can't have everyone using my Heroku deployment for this.

**Comment by alexfromvl** [comment]
@Dgolborne  The deployment was successful. Enter your process application is deployed. Sometimes even cases when the 500 error is returned if there is no access to the records in the file folder.
