### ISSUE TITLE
Custom Templates

### ISSUE THREAD

**Issue by mariajplmiranda** [nicolewhite/slack-meme#16]
I can't use "Custom Templates", I'm always getting "That template doesn't exist. Type `/meme templates` to see valid templates or provide your own as a URL." error message

**Comment by nicolewhite** [comment]
What exactly are you trying? I have no problem with custom templates. Make
sure the image is public.

**Comment by mariajplmiranda** [comment]
I'm trying your example: /meme http://nicolewhite.github.io/static/me.jpg; hello; my name is nicole;

I could check the network and the image is returning 304, does this make any difference?

**Comment by nicolewhite** [comment]
Try https://

**Comment by mariajplmiranda** [comment]
Yap, it is working! Sorry 👍

**Comment by nicolewhite** [comment]
No worries. I'll update the README.

**Comment by zedtux** [comment]
Well I'm facing this issue with the https.

```
/meme https://nicolewhite.github.io/images/me.jpg; hello; my name is nicole;
```

Failed with :

```
Template `<https://nicolewhite.github.io/images/me.jpg` doesn't exist. Type `/meme templates` to see valid templates or provide your own as a URL.
```

while a normal template works.

**Comment by aoberoi** [comment]
@zedtux tracking this in #30

**Comment by zedtux** [comment]
@aoberoi I have updated the code and now it's no more failing, when removing the semi-column after the image URL, and it's displaying "Success!" but no image is posted in Slack 🤔

**Comment by zedtux** [comment]
Oops ... sorry, I was testing within the wrong channel 🤦‍♂️. All is working fine 👍
