### ISSUE TITLE
Slackbot can't post memes?

### ISSUE THREAD

**Issue by terrorpaw** [nicolewhite/slack-meme#17]
So you can edit slackbot responses so that Slackbot automatically says something when a trigger word or phrase is posted to a channel by anyone else. Tried setting up a /meme command as a response but when slackbot responds, you just see the text. Any way to make it so that Slackbot can respond with memes?

**Comment by nicolewhite** [comment]
Hmm I've never thought of trying it that way. But if you've tried it and it doesn't work, I'm guessing I won't be able to get it to work either.

**Comment by terrorpaw** [comment]
I kinda figured. Thanks anyway for bringing the memes! 😉
