### ISSUE TITLE
Custom URLs: Invalid template name

### ISSUE THREAD

**Issue by michaelpjohnson** [nicolewhite/slack-meme#18]
Hello, when I run your example to pull a custom URL: `/meme https://nicolewhite.github.io/static/me.jpg; hello; my name is nicole;` I get the following error: 
`Invalid template name. Try `/meme success`, or type `/meme-list` to view all available meme templates.`

Any idea what happened?

**Comment by nicolewhite** [comment]
Ahh my bad! I changed that path on my personal blog. Try

```
/meme https://nicolewhite.github.io/images/me.jpg; hello; my name is nicole;
```
