### ISSUE TITLE
built-in templates don't work

### ISSUE THREAD

**Issue by wjrogers** [nicolewhite/slack-meme#21]
When I try to use one of the built-in templates, I get the message "that template doesn't exist," and the `/meme templates` command gives output like this:

```
`https://memegen.link/templates/aag` Ancient Aliens Guy
`https://memegen.link/templates/ackbar` It's A Trap!
`https://memegen.link/templates/afraid` Afraid to Ask Andy
`https://memegen.link/templates/alwaysonbeat` Drake Always On Beat
`https://memegen.link/templates/ants` Do You Want Ants?
...
```

Something seems amiss.

**Comment by nicolewhite** [comment]
I'm going to re-open this as it seems `/meme templates` is still broken.

**Comment by delseccoj** [comment]
I think this is the commit that adds the URL prefix

https://github.com/jacebrowning/memegen/commit/25ac6ca82d6c5202e4fcc055fd12800a539607ad

**Comment by jacebrowning** [comment]
Using `HTTPie`, `http GET https://memegen.link/templates/ --follow` returns a list of templates, so maybe the bot needs to follow redirects?

**Comment by jessmartin** [comment]
Thanks for the pointers @delseccoj and @jacebrowning. Made it easy to track down the issue! 👌
