### ISSUE TITLE
Previewing pictures

### ISSUE THREAD

**Issue by lassewesth** [nicolewhite/slack-meme#3]
If I forgot that success kid looks like, it might would be nice to be able to do `/meme success; foo; bar; preview`

**Comment by nicolewhite** [comment]
That's a good idea. I think the `preview` command should come first, though. So it'll be:

```
/meme preview success; foo; bar;
```

**Comment by jacebrowning** [comment]
Maybe there should be a semicolon between `preview` and the meme name?

**Comment by nicolewhite** [comment]
I think the semicolons should be preserved for the core syntax, `template; top; bottom;`, otherwise it might get confusing. Any help keywords should come immediately after `/meme`, so I'd like this to mirror the current help function `/meme templates`.

**Comment by lassewesth** [comment]
I reckon you need more angle brackets and/ or tabs:

```
/meme\t<preview value="true" />\ttemplate;\ttop;\tbottom
```
