### ISSUE TITLE
Custom Templates - Invalid template name

### ISSUE THREAD

**Issue by igogrek** [nicolewhite/slack-meme#30]
Calling `/meme https://nicolewhite.github.io/images/me.jpg; hello; my name is nicole;` or any other custom template gives me :
> Invalid template name. Try `/meme success`, or type `/meme-list` to view all available meme templates.

Any idea what's wrong?

**Comment by nicolewhite** [comment]
No. :( Will look into this shortly.

**Comment by afberg** [comment]
Any update on this?

**Comment by aoberoi** [comment]
@Igogrek is this only happening on Python 3.x? if so, this is probably the same issue as #42. if not, this is a separate issue.

**Comment by aoberoi** [comment]
this totally happened to me on Py 2.7.15, or, something close.

the response i got to the slash command was:

> Template `<https://nicolewhite.github.io/images/me.jpg` doesn't exist. Type `/meme templates` to see valid templates or provide your own as a URL.

noting the `<` before the URL, its probably an issue dealing with the formatting of URLs.
