### ISSUE TITLE
Is this memetizer.com?

### ISSUE THREAD

**Issue by bj-mcduck** [nicolewhite/slack-meme#31]
We're using the `Meme Bot` for slack, which can be found on [memetizer](http://www.memetizer.com/).
They have no link for a repo, or how to contribute... are you affiliated?

**Comment by jacebrowning** [comment]
As far as I know, memetizer is closed source and is not the same thing as slack-meme:

https://github.com/jacebrowning/memegen#sample-clients

If you're looking to add templates to memetizer and slack-meme, there are instructions here: 

https://github.com/jacebrowning/memegen/blob/master/CONTRIBUTING.md#adding-templates
