### ISSUE TITLE
update README to reflect new Slack App creation process

### ISSUE THREAD

**Issue by aoberoi** [nicolewhite/slack-meme#33]
this project is great! i'm hoping to use it as an example in a talk, so i'm very thankful for your open source work.

i suggest that we rework the README with updated instructions and screenshots of the Slack App creation process. some of the terminology could be improved as over time the API has changed.

if you're open to contributions, i can send a PR with what i have in mind

**Comment by nicolewhite** [comment]
Please do! I've wanted to update this for the longest time but never got
around to it. Happy to leave it to you.
