### ISSUE TITLE
please check screenshot error

### ISSUE THREAD

**Issue by nk932714** [nicolewhite/slack-meme#38]
how to get the webhook url

![image](https://user-images.githubusercontent.com/29853208/30146064-723cacf6-93b3-11e7-822d-864134379630.png)

**Comment by aoberoi** [comment]
this means your team has the "admin approved apps" feature turned on. you'll have to contact your workspace owner to get permission to create an app on that team.

if you're just trying to start developing, its pretty easy to create a new free team which won't have that restriction. then when you have something useful, you're workspace owner is more likely to let you install it.
