### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by coreymckrill** [nicolewhite/slack-meme#4]
I ran through the setup on the readme page. The `templates` and `preview` subcommands work, but the actual `/meme` command gives me an error like this:

![error](https://cloud.githubusercontent.com/assets/916023/9364819/b5e04330-465a-11e5-8281-86ab79928242.png)

Any ideas?

**Comment by jacebrowning** [comment]
Were you passing any arguments to the `/meme` command?

**Comment by coreymckrill** [comment]
Yep, I tried the example from the readme: `/meme success; we have; a meme bot;`

**Comment by nicolewhite** [comment]
I can get it to 500 on `/meme` alone but not on `/meme success; we have; a meme bot;`.

**Comment by coreymckrill** [comment]
Hmm. Maybe it's something with my Heroku config. Which I don't know anything about ... yet. :(

**Comment by giggio** [comment]
I am getting the same error. It works with `preview`, like that:

```
/meme preview success;we-have;a-meme-bot;
```

But not without:

```
/meme success;we-have;a-meme-bot;
```

**Comment by nicolewhite** [comment]
What happens if you try just `/meme success;`?

**Comment by giggio** [comment]
Same error with `/meme success;`:

```
<DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p> 
```

**Comment by nicolewhite** [comment]
Maybe try wrapping this part of `views.py` in a try-except:

``` python
try:
    slack.post_meme_to_webhook(payload)
except Exception as e:
    return e
```

**Comment by coreymckrill** [comment]
I made the edit and deployed it to my Heroku instance. Still getting the same error though. :disappointed:

**Comment by nicolewhite** [comment]
I'm not sure what to do; I can't reproduce. :(

**Comment by Nojj02** [comment]
Same problem here. I don't know how to debug the app though. I'm experiencing the exact same symptoms as the others.

**Comment by nicolewhite** [comment]
Run the app locally and switch `debug=True` so we can get the actual error message.

Edit: To elaborate, you should change the line in `run.py` to 

``` python
app.run(host='0.0.0.0', port=port, debug=True)
```

and start the app locally. It should start on port 5000. Then, go grab something from your Heroku logs that 500'd, ideally a request that was to the slackbot channel so it doesn't show up elsewhere. Copy the contents into the browser, which should send a GET request to the `/` endpoint and you'll get a stacktrace of exactly what's wrong.

**Comment by coreymckrill** [comment]
Ok, I actually just set `debug` to `True` on my Heroku app, rather than locally, since I'm not using it for anything else.

So to confirm the behavior I found earlier, when I do a GET request for the preview command, with a query string that looks like this:
`/?other=stuff&command=%2Fmeme&text=preview+success%3B`

I get the expected response:
`http://memegen.link/success/_/_.jpg`

With the query string for the live meme command:
`/?other=stuff&command=%2Fmeme&text=success%3B`

I get lots of debug:

```
requests.exceptions.InvalidSchema

InvalidSchema: No connection adapters were found for ' https://hooks.slack.com/services/[token stuff here]'

Traceback (most recent call last)

    File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__

    return self.wsgi_app(environ, start_response)

    File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app

    response = self.make_response(self.handle_exception(e))

    File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app

    response = self.full_dispatch_request()

    File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request

    rv = self.dispatch_request()

    File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "/app/slack/views.py", line 54, in meme

    slack.post_meme_to_webhook(payload)

    File "/app/slack/models.py", line 77, in post_meme_to_webhook

    requests.post(self.WEBHOOK_URL, data=json.dumps(payload))

    File "/app/.heroku/python/lib/python2.7/site-packages/requests/api.py", line 109, in post

    return request('post', url, data=data, json=json, **kwargs)

    File "/app/.heroku/python/lib/python2.7/site-packages/requests/api.py", line 50, in request

    response = session.request(method=method, url=url, **kwargs)

    File "/app/.heroku/python/lib/python2.7/site-packages/requests/sessions.py", line 465, in request

    resp = self.send(prep, **send_kwargs)

    File "/app/.heroku/python/lib/python2.7/site-packages/requests/sessions.py", line 567, in send

    adapter = self.get_adapter(url=request.url)

    File "/app/.heroku/python/lib/python2.7/site-packages/requests/sessions.py", line 641, in get_adapter

    raise InvalidSchema("No connection adapters were found for '%s'" % url)

    InvalidSchema: No connection adapters were found for ' https://hooks.slack.com/services/[token stuff here] '
```

**Comment by nicolewhite** [comment]
And you're using requests 2.7.0?

**Comment by coreymckrill** [comment]
Yep. Confirmed via CLI: `heroku run pip show requests`

**Comment by nicolewhite** [comment]
Hm. Which version of Python?

**Comment by coreymckrill** [comment]
2.7.10

**Comment by nicolewhite** [comment]
I'm still unable to reproduce. Can you show me some reproducible code to get that error? I'm on Python v2.7.10 with requests v2.7.0 and am failing to get that error message.

**Comment by coreymckrill** [comment]
^ I think this will fix it.

**Comment by giggio** [comment]
Yep, that fixed it. Thanks!

**Comment by nicolewhite** [comment]
:clap:
