### ISSUE TITLE
Template error (Python 3 compatibility)

### ISSUE THREAD

**Issue by gegnew** [nicolewhite/slack-meme#42]
When I type /meme templates, I get a list of templates that looks like this:
![memer2](https://user-images.githubusercontent.com/35822787/42648534-774c3104-85c4-11e8-967d-8f805e8c5b1f.png)

Rather than like this:
![memer1](https://user-images.githubusercontent.com/35822787/42648533-771866c6-85c4-11e8-888d-31aacc1b6f0f.png)

Then, when I run a template (say /meme success;we have;a meme bot) I get the error "Template `success` doesn't exist. Type `/meme templates` to see valid templates or provide your own as a URL."

Any idea what's going on with the meme template names?

Thanks!

**Comment by aoberoi** [comment]
out of curiosity, which version of python are you running?

**Comment by gegnew** [comment]
Well, it's interesting that you ask. I am running v 3.5.2, but my 
command for it is "python3". "python" runs v 2.7.12. It seems that 
could be the issue.

-g

**Comment by PaulBrandt** [comment]
For us this was fixed by changing Heroku to use python 2.7.15 instead of 3.*
Templates list correctly and using them works as well.
But the code is not python3 compatible atm.
