### ISSUE TITLE
The meme I'm posting are "Only visible to you"

### ISSUE THREAD

**Issue by zedtux** [nicolewhite/slack-meme#49]
<img width="639" alt="slack_-_pharmony" src="https://user-images.githubusercontent.com/478564/42953812-7f0acf60-8b7b-11e8-88a5-14d2808c5eb2.png">

How can I fix that please ?

**Comment by aoberoi** [comment]
i think that "Only visible to you" is referring to the following message, not the meme. notice the light gray background color that extends to the next message. an easy way to test is if you reload (Cmd+R or Ctrl+R), then the messages which were only visible to you should go away.

**Comment by zedtux** [comment]
Oh yeah, 100% right @aoberoi 👍 Thank you so much !
