### ISSUE TITLE
How do I upgrade an existing Heroku deployment?

### ISSUE THREAD

**Issue by jacebrowning** [nicolewhite/slack-meme#7]
Would it be worth adding instructions somewhere?

**Comment by nicolewhite** [comment]
Yeah, good idea. I've actually never had to do that. What do you suggest?

**Comment by nicolewhite** [comment]
And by that I mean I've never had to update an app that I didn't own and have set up through git.

**Comment by jacebrowning** [comment]
I'm thinking it's just a few lines of Git commands somewhere on the README similar to

``` sh
# (untested)
git clone <my app's heroku repo>
git fetch nicolewhite/slack-meme
git merge nicolewhite/master
git push
```

**Comment by nicolewhite** [comment]
This is what I've got. What do you think?

To update your deployment with changes from this repository, visit your app's homepage on Heroku and navigate to the Deploy section. Follow the instructions under Heroku Git - Use Heroku Toolbelt. In particular:

```
$ heroku login
$ heroku git:clone -a <your app name>
$ cd <your app name>
```

Once you have this set up, you can update your app with changes from this repository with the following:

```
$ git remote add slack-meme https://github.com/nicolewhite/slack-meme
$ git pull slack-meme master
$ git push heroku master
```

**Comment by jacebrowning** [comment]
> ...visit your app's homepage on Heroku and navigate to the Deploy section.

You may want to give an example of this:

https://dashboard.heroku.com/apps/YOUR-APP/deploy/heroku-git

> Once you have this set up, you can update your app with changes from this repository with the following...

Weirdly, I had merge conflicts when executing the bottom section of commands:

``` sh
$ git pull slack-meme master
From https://github.com/nicolewhite/slack-meme
 * branch            master     -> FETCH_HEAD
First, rewinding head to replay your work on top of it...
Applying: Import source code
Using index info to reconstruct a base tree...
<stdin>:89: trailing whitespace.
[Create a new Incoming Webhook](https://my.slack.com/services/new/incoming-webhook/). You can choose any channel; it doesn't matter.
<stdin>:90: trailing whitespace.
The channel will be overridden on each request with the channel from which the request originated. After creating, you'll see
warning: 2 lines add whitespace errors.
Falling back to patching base and 3-way merge...
Auto-merging slack/views.py
CONFLICT (add/add): Merge conflict in slack/views.py
Auto-merging slack/models.py
CONFLICT (add/add): Merge conflict in slack/models.py
Failed to merge in the changes.
Patch failed at 0001 Import source code
The copy of the patch that failed is found in:
   /Users/Browning/Programs/slackmeme-votestakes/.git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```

I hadn't made any changes of my own since I deployed from this repo a few days ago, so this was surprising. What I actually ended up running was:

```
$ git remote add slack-meme https://github.com/nicolewhite/slack-meme
$ git fetch slack-meme master
$ git reset --hard slack-meme/master
$ git push heroku master --force
```

but I think your commands would work if there was no conflict.

After pushing this, https://github.com/nicolewhite/slack-meme/issues/6 is now fixed for me, which confirms the upgrade worked.

**Comment by nicolewhite** [comment]
Maybe your IDE inserted whitespace? I think this can be avoided by switching to `git pull --rebase slack-meme master`.
