### ISSUE TITLE
Non-heroku deployment

### ISSUE THREAD

**Issue by gotakk** [nicolewhite/slack-meme#9]
Hello,

I am happy to know your project. But I have a ubuntu server where I put my cloud services (like bots etc...)
How can I deploy your project on my ubuntu server ?

Thanks

**Comment by nicolewhite** [comment]
That's beyond the scope of this project. I'd check out gunicorn and nginx. A quick Google search lead me to this:

https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-ubuntu-14-04

Good luck!
